name: nix

on:
  push:
    paths:
      - "**.py"
      - "**.rst"
      - "**.nix"
      - "**.lock"
      - "pyproject.toml"
      - "poetry.lock"
      - ".pre-commit-config.yaml"
      - ".github/workflows/*.yaml"
      # Ignore small changes to documentation files
      # (ReadTheDocs will build based on new README anyway.)
      - "!README.rst"
      - "!CHANGELOG.md"
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build doit-ext with nix
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Run the magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v1
      - name: Build with nix
        run: |
          nix flake check
