name: nix

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test doit-ext with poetry
    strategy:
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
      - name: Run the magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Test with poetry on Python ${{ matrix.python-version }}
        run: |
          nix run .#poetry-run -- ${{ matrix.python-version }} pytest
